# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import internvla_pb2 as internvla__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

# 兼容旧环境（如 Go2 Python 3.8）：grpcio 低于生成版本时仅警告，不阻断
if _version_not_supported:
    warnings.warn(
        f'grpc {GRPC_VERSION} < generated {GRPC_GENERATED_VERSION}; consider upgrading to grpcio>={GRPC_GENERATED_VERSION}.',
        UserWarning,
        stacklevel=2,
    )


class InternVLAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitEpisode = channel.unary_unary(
                '/internvla.InternVLAService/InitEpisode',
                request_serializer=internvla__pb2.InitRequest.SerializeToString,
                response_deserializer=internvla__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/internvla.InternVLAService/Step',
                request_serializer=internvla__pb2.StepRequest.SerializeToString,
                response_deserializer=internvla__pb2.StepResponse.FromString,
                _registered_method=True)


class InternVLAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternVLAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.InitEpisode,
                    request_deserializer=internvla__pb2.InitRequest.FromString,
                    response_serializer=internvla__pb2.InitResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=internvla__pb2.StepRequest.FromString,
                    response_serializer=internvla__pb2.StepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internvla.InternVLAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('internvla.InternVLAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternVLAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internvla.InternVLAService/InitEpisode',
            internvla__pb2.InitRequest.SerializeToString,
            internvla__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internvla.InternVLAService/Step',
            internvla__pb2.StepRequest.SerializeToString,
            internvla__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
