# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internvla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# 兼容旧环境（Python 3.8 + protobuf 5.x）：无 runtime_version 或版本低于 gencode 时跳过校验
try:
    from google.protobuf import runtime_version as _runtime_version
    try:
        _runtime_version.ValidateProtobufRuntimeVersion(
            _runtime_version.Domain.PUBLIC,
            6,
            31,
            1,
            '',
            'internvla.proto'
        )
    except Exception:
        pass  # VersionError: runtime 5.x < gencode 6.31.1，跳过校验仍可运行
except ImportError:
    pass
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finternvla.proto\x12\tinternvla\"6\n\x0bInitRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0binstruction\x18\x02 \x01(\t\"\x1a\n\x0cInitResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"q\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0b\n\x03rgb\x18\x04 \x01(\x0c\x12\r\n\x05\x64\x65pth\x18\x05 \x01(\x0c\x12\x13\n\x0b\x63\x61mera_pose\x18\x06 \x03(\x02\"\x80\x01\n\x0cStepResponse\x12\x16\n\x0ehas_trajectory\x18\x01 \x01(\x08\x12\x12\n\ntrajectory\x18\x02 \x03(\x02\x12\x12\n\nhas_action\x18\x03 \x01(\x08\x12\x0e\n\x06\x61\x63tion\x18\x04 \x03(\x05\x12\x0f\n\x07pixel_x\x18\x05 \x01(\x05\x12\x0f\n\x07pixel_y\x18\x06 \x01(\x05\x32\x8b\x01\n\x10InternVLAService\x12>\n\x0bInitEpisode\x12\x16.internvla.InitRequest\x1a\x17.internvla.InitResponse\x12\x37\n\x04Step\x12\x16.internvla.StepRequest\x1a\x17.internvla.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internvla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=30
  _globals['_INITREQUEST']._serialized_end=84
  _globals['_INITRESPONSE']._serialized_start=86
  _globals['_INITRESPONSE']._serialized_end=112
  _globals['_STEPREQUEST']._serialized_start=114
  _globals['_STEPREQUEST']._serialized_end=227
  _globals['_STEPRESPONSE']._serialized_start=230
  _globals['_STEPRESPONSE']._serialized_end=358
  _globals['_INTERNVLASERVICE']._serialized_start=361
  _globals['_INTERNVLASERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
